"""The desktop must be able to verify a signature the phone actually made.

This file exists because of a failure that every other test missed. Both
implementations passed their own suites, agreed byte-for-byte on the wire
format, agreed on the pairing code, and agreed on the exact bytes that get
signed — and pairing still failed on the first real attempt with
`auth_failed bad_signature`.

The signature was fine. The certificate could not be parsed at all. Ktor's
certificate helper writes a signature AlgorithmIdentifier with a parameters
field, which is correct for RSA and forbidden for ECDSA. Java's parser accepts
it, so Kotlin verified its own certificates happily; Python's parser rejects
it, and `verify_signature` catches the ValueError and reports a bad signature —
pointing at the wrong thing entirely.

No amount of same-language testing would have caught that. Only one side
producing material and the other side consuming it does.

The fixture is generated by the Kotlin suite:

    gradle :core:test --tests "com.airgrab.core.CrossSignatureTest"

which writes android/core/build/interop/kotlin-signature.json. The test skips
when that file is absent, so the Python suite still runs on a machine with no
Android toolchain.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from cryptography import x509

from airgrab.auth import signing_payload
from airgrab.identity import fingerprint_of, verify_signature

FIXTURE = (
    Path(__file__).parents[2]
    / "android" / "core" / "build" / "interop" / "kotlin-signature.json"
)


def _fixture() -> dict:
    if not FIXTURE.is_file():
        pytest.skip(
            "Kotlin signature fixture not built. Run:\n"
            "  gradle :core:test --tests \"com.airgrab.core.CrossSignatureTest\""
        )
    return json.loads(FIXTURE.read_text())


def test_a_kotlin_certificate_parses():
    """The failure that started this: strict parsers must accept it.

    Asserted separately from the signature because a certificate that cannot
    be read is reported by verify_signature as a bad signature, which sends
    anyone debugging it to the wrong place.
    """
    data = _fixture()
    certificate = x509.load_der_x509_certificate(bytes.fromhex(data["cert_der"]))

    assert certificate.signature_algorithm_oid._name == "ecdsa-with-SHA256"
    assert certificate.public_key().curve.name == "secp256r1"


def test_a_kotlin_fingerprint_is_what_python_computes():
    data = _fixture()
    assert fingerprint_of(bytes.fromhex(data["cert_der"])) == data["client_fp"]


def test_the_signing_payload_agrees_across_languages():
    data = _fixture()
    payload = signing_payload(data["nonce"], data["server_fp"], data["client_fp"])
    assert payload.hex() == data["payload"]


def test_python_verifies_a_signature_kotlin_made():
    """The whole point. This is exactly what happens during pairing."""
    data = _fixture()
    payload = signing_payload(data["nonce"], data["server_fp"], data["client_fp"])

    assert verify_signature(
        bytes.fromhex(data["cert_der"]), payload, bytes.fromhex(data["signature"])
    )


def test_a_tampered_payload_is_rejected():
    """Confirms the check above is doing real work, not passing vacuously."""
    data = _fixture()
    other = signing_payload(data["nonce"], data["server_fp"], "0" * 64)

    assert not verify_signature(
        bytes.fromhex(data["cert_der"]), other, bytes.fromhex(data["signature"])
    )
