package com.airgrab.core

import java.io.File
import java.nio.file.Files
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Emit a real signature for Python to verify, and pin what gets signed.
 *
 * This is the gap that let a live pairing fail with `auth_failed
 * bad_signature` while every test on both sides passed. `compute_sas` and the
 * wire envelope were pinned across the two languages; the authentication
 * payload never was. Both implementations were self-consistent and disagreed
 * with each other, which is precisely the failure a cross-language vector
 * exists to prevent.
 *
 * The output is written for `desktop/tests/test_cross_signature.py` to read.
 */
class CrossSignatureTest {

    private val temp: File = Files.createTempDirectory("airgrab-crosssig").toFile()

    @AfterTest
    fun cleanUp() {
        temp.deleteRecursively()
    }

    private fun ByteArray.hex(): String = joinToString("") { "%02x".format(it) }

    @Test
    fun `the signing payload is a stable, documented sequence of bytes`() {
        val nonce = "a".repeat(64)
        val serverFp = "b".repeat(64)
        val clientFp = "c".repeat(64)

        val payload = Auth.signingPayload(nonce, serverFp, clientFp)

        // SHA-256 of "airgrab-auth-v1" + nonce + serverFp + clientFp, UTF-8.
        assertEquals(32, payload.size)
        assertEquals(
            java.security.MessageDigest.getInstance("SHA-256")
                .digest(("airgrab-auth-v1$nonce$serverFp$clientFp").toByteArray(Charsets.UTF_8))
                .hex(),
            payload.hex(),
        )
    }

    @Test
    fun `the order of the two fingerprints matters`() {
        val nonce = Auth.newNonce()
        val a = "b".repeat(64)
        val b = "c".repeat(64)

        // Unlike the pairing code, this is deliberately NOT order-independent:
        // swapping them is what would let a captured signature be replayed in
        // the opposite direction.
        assertTrue(
            !Auth.signingPayload(nonce, a, b).contentEquals(Auth.signingPayload(nonce, b, a))
        )
    }

    @Test
    fun `writes a real signature for the python implementation to verify`() {
        val identity = FileIdentity.loadOrCreate(temp, "KOTLIN-PHONE")

        val nonce = "0123456789abcdef".repeat(4)
        val serverFp = "f".repeat(64)
        val clientFp = identity.fingerprint

        val payload = Auth.signingPayload(nonce, serverFp, clientFp)
        val signature = identity.sign(payload)

        // Self-check first: a failure here means the problem is local, not a
        // disagreement between languages.
        assertTrue(
            Certificates.verifySignature(identity.certDer, payload, signature),
            "Kotlin cannot verify its own signature",
        )

        val out = File("build/interop/kotlin-signature.json")
        out.parentFile.mkdirs()
        out.writeText(
            """
            {
              "note": "Generated by CrossSignatureTest. Python must verify this.",
              "nonce": "$nonce",
              "server_fp": "$serverFp",
              "client_fp": "$clientFp",
              "payload": "${payload.hex()}",
              "cert_der": "${identity.certDer.hex()}",
              "signature": "${signature.hex()}"
            }
            """.trimIndent() + "\n"
        )
        assertTrue(out.exists())
    }
}
