package com.airgrab.core

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull

/**
 * Byte-level agreement with the Python implementation.
 *
 * The unit tests on either side prove each implementation is self-consistent,
 * which is not the same thing as the two agreeing. A phone and a PC that each
 * pass their own suite can still be unable to speak to one another, and the
 * symptom — a connection that stalls or a peer that ignores a message — points
 * nowhere near the encoder.
 *
 * `protocol/vectors/envelopes.json` is generated by
 * `desktop/airgrab/protocol.py` and contains the EXACT strings it produces.
 * If Kotlin ever emits a different byte for the same input, this fails.
 */
class InteropVectorsTest {

    private fun vectors(name: String): File {
        val candidates = listOf(
            File("../../protocol/vectors/$name"),
            File("../protocol/vectors/$name"),
            File("protocol/vectors/$name"),
        )
        return candidates.firstOrNull { it.exists() }
            ?: error("$name not found; looked in ${candidates.map { it.absolutePath }}")
    }

    /** Rebuild the payload map the Python generator recorded for a case. */
    private fun payloadOf(obj: JsonObject): Map<String, Any?> =
        obj["payload"]!!.jsonObject.mapValues { (_, value) ->
            val primitive = value.jsonPrimitive
            when {
                primitive.isString -> primitive.content
                primitive.booleanOrNull != null -> primitive.booleanOrNull
                primitive.intOrNull != null -> primitive.intOrNull
                primitive.longOrNull != null -> primitive.longOrNull
                else -> primitive.content
            }
        }

    @Test
    fun `encodes byte-identically to the python implementation`() {
        val root = Json.parseToJsonElement(vectors("envelopes.json").readText()).jsonObject
        val cases = root["cases"]!!.jsonArray
        assertTrue(cases.isNotEmpty(), "no envelope vectors were parsed")

        for (element in cases) {
            val case = element.jsonObject
            val type = case["type"]!!.jsonPrimitive.content
            val seq = case["seq"]!!.jsonPrimitive.int
            val expected = case["encoded"]!!.jsonPrimitive.content

            assertEquals(
                expected,
                Protocol.encode(type, seq, payloadOf(case)),
                "encoding differs from Python for message type '$type'",
            )
        }
    }

    @Test
    fun `decodes every envelope python produces`() {
        val root = Json.parseToJsonElement(vectors("envelopes.json").readText()).jsonObject
        for (element in root["cases"]!!.jsonArray) {
            val case = element.jsonObject
            val encoded = case["encoded"]!!.jsonPrimitive.content
            val envelope = Protocol.decode(encoded)

            assertEquals(case["type"]!!.jsonPrimitive.content, envelope.type)
            assertEquals(case["seq"]!!.jsonPrimitive.int, envelope.seq)
        }
    }

    @Test
    fun `round trips every python envelope back to the same string`() {
        val root = Json.parseToJsonElement(vectors("envelopes.json").readText()).jsonObject
        for (element in root["cases"]!!.jsonArray) {
            val encoded = element.jsonObject["encoded"]!!.jsonPrimitive.content
            val decoded = Protocol.decode(encoded)
            assertEquals(
                encoded,
                Protocol.encode(decoded.type, decoded.seq, decoded.payload),
                "decode then encode did not reproduce the original bytes",
            )
        }
    }

    @Test
    fun `reads a trust store written by the python implementation`() {
        val file = vectors("trust-sample.json")
        val store = TrustStore(file)
        val peers = store.all()

        assertEquals(2, peers.size, "expected the two peers Python wrote")
        assertTrue(store.isTrusted("a".repeat(64)))
        assertEquals("PADMA-PC", store.get("a".repeat(64))?.name)
        assertEquals("windows", store.get("a".repeat(64))?.platform)
        assertEquals("iQOO Neo 10", store.get("b".repeat(64))?.name)
        assertEquals("android", store.get("b".repeat(64))?.platform)
    }

    @Test
    fun `writes a trust store for the python implementation to read back`() {
        // Deliberately writes outside the temp directory so the file survives
        // the test run and the Python side can be pointed at it. Reading a
        // Python-written file proves one direction; this proves the other, and
        // a format that only works one way would pair once and then fail.
        val out = File("build/interop/trust-from-kotlin.json")
        out.parentFile.mkdirs()
        out.delete()

        val store = TrustStore(out)
        store.add("c".repeat(64), "KOTLIN-PHONE", "android")
        store.add("d".repeat(64), "KOTLIN-PC", "windows")

        assertTrue(out.exists(), "trust store was not written")
        val reread = TrustStore(out)
        assertEquals(2, reread.all().size)
        assertEquals("KOTLIN-PHONE", reread.get("c".repeat(64))?.name)
    }
}

private val kotlinx.serialization.json.JsonPrimitive.int: Int
    get() = requireNotNull(intOrNull) { "expected an integer, got $content" }
