package com.airgrab.core

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The cross-language guard rail.
 *
 * These vectors are generated by the Python implementation and committed to
 * `protocol/vectors/sas.json`. If this Kotlin port ever computes a different
 * pairing code, the two halves of AirGrab silently stop being able to pair —
 * and the symptom is two mismatched six-digit numbers on two screens, with
 * nothing to indicate which side is wrong. This test turns that into a build
 * failure instead.
 */
class SasVectorsTest {

    private fun vectorsFile(): File {
        // Tests run with the module directory as CWD; the vectors live at the
        // repository root, shared with the Python implementation.
        val candidates = listOf(
            File("../../protocol/vectors/sas.json"),
            File("../protocol/vectors/sas.json"),
            File("protocol/vectors/sas.json"),
        )
        return candidates.firstOrNull { it.exists() }
            ?: error("sas.json not found; looked in ${candidates.map { it.absolutePath }}")
    }

    /** Minimal extraction: the file is generated, so its shape is fixed. */
    private fun parseCases(text: String): List<Triple<String, String, String>> {
        val pattern = Regex(
            """\{\s*"a"\s*:\s*"([0-9a-f]+)"\s*,\s*"b"\s*:\s*"([0-9a-f]+)"\s*,\s*"sas"\s*:\s*"(\d{6})"\s*\}"""
        )
        return pattern.findAll(text)
            .map { Triple(it.groupValues[1], it.groupValues[2], it.groupValues[3]) }
            .toList()
    }

    @Test
    fun `matches every vector produced by the python implementation`() {
        val cases = parseCases(vectorsFile().readText())
        assertTrue(cases.isNotEmpty(), "no vectors were parsed")
        for ((a, b, expected) in cases) {
            assertEquals(expected, Sas.compute(a, b), "SAS mismatch for $a / $b")
        }
    }

    @Test
    fun `is six digits`() {
        val sas = Sas.compute("a".repeat(64), "b".repeat(64))
        assertEquals(6, sas.length)
        assertTrue(sas.all { it.isDigit() })
    }

    @Test
    fun `is independent of who initiated`() {
        val a = "deadbeef".repeat(8)
        val b = "cafebabe".repeat(8)
        assertEquals(Sas.compute(a, b), Sas.compute(b, a))
    }

    @Test
    fun `high bytes are not sign-extended`() {
        // Kotlin's Byte is signed. Without masking each byte back to 0..255 a
        // digest starting above 0x7F produces a negative intermediate and the
        // wrong code, which is exactly the kind of bug the vectors exist for.
        val sas = Sas.compute("f".repeat(64), "f".repeat(64))
        assertEquals(6, sas.length)
        assertTrue(sas.toInt() in 0..999_999)
    }

    @Test
    fun `signing payload is thirty-two bytes and binds both fingerprints`() {
        val a = "1".repeat(64)
        val b = "2".repeat(64)
        val nonce = "ab".repeat(32)
        val payload = Sas.signingPayload(nonce, a, b)
        assertEquals(32, payload.size)
        // Swapping the roles must change the payload, or a signature captured
        // as client could be replayed as server.
        assertTrue(!payload.contentEquals(Sas.signingPayload(nonce, b, a)))
    }

    @Test
    fun `fingerprint is lowercase hex of length sixty-four`() {
        val fingerprint = Sas.fingerprintOf(byteArrayOf(1, 2, 3, -1, -128))
        assertEquals(64, fingerprint.length)
        assertEquals(fingerprint.lowercase(), fingerprint)
    }
}
